server:
  port: 8280



---
spring:
  profiles: default
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true

  datasource:
    url: jdbc:mysql://uengine.cxp0klyrcjfk.ap-northeast-2.rds.amazonaws.com:3306/uengine
    username: root
    password: my-secret-pw
    # mybatis 설정시에는 driverClassName 을 넣어주어야함
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: a487b083438bf11e9a56802910c21b39-1550178129.ap-northeast-2.elb.amazonaws.com
    port: 6379
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
    password: secretpassword
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
    type: redis

mybatis:
  configuration:
    # user_name 을 userName 으로 조회하기 위해서는 camel-case 옵션을 줘야함
    map-underscore-to-camel-case: true


---
spring:
  profiles: docker
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
  datasource:
    url: jdbc:mysql://db.pas-mini.io:10002/uengine
    username: root
    password: my-secret-pw
  redis:
      host: my-redis-master
#      host: afcc3ec620efd11e9884d02be6ea23ef-922140091.ap-northeast-2.elb.amazonaws.com
      port: 6379
      lettuce:
        pool:
          max-active: 7
          max-idle: 7
          min-idle: 2
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
    type: redis